tf-wallet-dscanner/tf-wallet

src/ui/components/atoms/tabs/index.ts
src/ui/components/atoms/tabs/tabs.scss
src/ui/components/atoms/tabs/tabs.tsx
src/ui/pages/hong.tsx

Tab 컴포넌트 추가
- props로 tabData전달 (title, component)
- value 값은 활성화 시킬 탭 index, 값 안보내면 0번지 초기값 지정
- indicator TransitionEnd 시점에 부모에서 전달한 onChange 이벤트 발생시킴
close #9-tab

feat: Tab 컴포넌트 추가

---

src/ui/components/atoms/tooltip/index.ts
src/ui/components/atoms/tooltip/tooltip.scss
src/ui/components/atoms/tooltip/tooltip.tsx
src/ui/components/atoms/typography/typography.tsx
src/ui/pages/home.tsx
tailwind.config.js

atoms/tooltip 컴포넌트를 추가함
1. placement: 툴팁이 나타나는 위치를 의미함(default: bottom)
2. message: tooltip에 표시할 message. string | ReactElement
closes #8

tooltip 컴포넌트 추가

---

.eslintrc.js
config/webpack.config.js
package.json
public/manifest.json
src/app/background.js
src/app/contentscript.js
src/app/controller.js
src/app/lib/localstore.js
src/app/messages.js
src/app/messenger.js
src/ui/pages/about.jsx

- ui/bg communication
- storage get, set

feat: broswer sample

---

src/app/background.js
src/app/controller.js
src/app/controllers/keyring-controller.js
src/ui/components/atoms/text-field/text-field.jsx
src/ui/pages/import-account.jsx
src/ui/pages/new-account.jsx

background에 keyringController 관련해서 bind하던 로직들 Controller 내부로 옮김
ref #36

refactor: keyring 관련 코드 background -> controller 이동

---

package.json
src/app/controllers/provider-controller.test.js
src/app/lib/util.js
src/app/mocks/MockStore.js

Provider 설정 값을 store에 get, set 하면서 데이터가 정상적으로 도출되는지 테스트 작성
1. MockStore class 추가
2. Provider Controller test 작성

test: provider controller test 작성

---

src/app/background.js
src/app/controller.js
src/app/controllers/keyring-controller.js
src/app/lib/eth-query.js
src/app/messages.js
src/ui/data/account/account.api.js
src/ui/pages/home.jsx
src/ui/pages/json-file.jsx
src/ui/pages/routing.jsx
src/ui/utils/util.js

keystoreV3.json export 다운로드 추가
ref #36

feat: keystoreV3.json export 

---

src/app/controller.js
src/app/controllers/keyring-controller.js
src/app/controllers/provider-controller.js
src/app/controllers/transaction-controller.js
src/app/lib/hd-keyring.js
src/app/lib/simple-keyring.js
src/ui/data/provider/provider.api.js
src/ui/data/provider/provider.hooks.js
src/ui/data/transaction/index.js
src/ui/data/transaction/transaction.api.js
src/ui/data/transaction/transaction.hooks.js
src/ui/pages/json-file.jsx
src/ui/pages/provider.jsx

feat: keyring-controller transaction sign 기능 추가
- TransactionController 추가
- vault 정보와 password를 통해서 keyring restore 기능 추가
- store accounts 정보에서 private key 추출하여 sign 진행
refs #50-transaction-sign

keyring-controller transaction sign 기능 추가

---

package.json
src/app/controllers/keyring-controller.js
src/app/controllers/keyring-controller.test.js
src/app/lib/web3-query.js
src/app/mocks/mock-encryptor.js

니모닉 생성 및 검증, 신규 계정 생성, 계정복구, 개인키 / 공개키 추출, 비공개키로 계정 가져오기
- package.json에서 jest testEnvironment를 node로 변경 (private key UinitArray 에러 해결위해)
- test용 mock-encryptor 추가
- address 유효성 검사 위해 web3.utils.isAddress 사용한 EthQuery 추가

test: keyring-controller test 작성

---

src/app/controllers/keyring-controller.js
src/ui/pages/json-file.jsx

refactor: vault 관련 수정
1. keyring clear 시점이 vault 생성에 문제가 되어 삭제
2. 비공개키로 import 시 패스워드는 불필요하여 input 제거

vault 관련 수정

---

src/app/constants/gas.js
src/app/controller.js
src/app/controllers/transactions/transaction-controller.js
src/app/controllers/transactions/tx-gas-utils.js
src/ui/pages/home.jsx
src/ui/pages/transaction/estimate-gas.jsx
src/ui/pages/transaction/input-address.jsx
src/ui/store/transaction.js

트랜잭션 가스비를 추정하는 로직에서 에러가 발생하여 수정
1. estimateGas 과정에서 잘못된값을 setGasPrice 하는 부분 수정
2. eth_estimateGas 에서 data 필드에 0x0 과 같이 홀수로 세팅할 경우 16진수 변환에서 에러발생하여 0x00으로 변경
close #72

estimateGas error fix

---

src/app/controller.js
src/app/controllers/keyring-controller.js
src/app/controllers/transactions/transaction-controller.js
src/ui/pages/home.jsx
src/ui/pages/json-file.jsx

home 화면에 balance 표기
- 네트워크에 맞춰 balance 값 업데이트
- private key로 계정 가져오는 부분 문제 있어서 password 받는 input 다시 추가함
close #74 

feat: home 화면에 balance 표기

---

nodemon.json
public/notification.html
public/popup.html
src/app/controllers/keyring-controller.js
src/app/controllers/transactions/transaction-controller.js
src/ui/components/account-view/account-view.jsx
src/ui/components/account-view/balance/balance.jsx
src/ui/components/account-view/selected-account/selected-account.jsx
src/ui/components/account-view/selected-account/selected-account.scss
src/ui/components/atoms/container/container.jsx
src/ui/components/atoms/container/container.scss
src/ui/components/atoms/typography/typography.scss
src/ui/components/header/header.jsx
src/ui/components/header/header.scss
src/ui/data/transaction/transaction.api.js
src/ui/pages/home.jsx
src/ui/pages/routing.jsx
src/ui/pages/transaction/estimate-gas.jsx
src/ui/pages/transaction/input-address.jsx
src/ui/pages/transaction/transaction.jsx
src/ui/pages/transaction/tx-result.jsx
tailwind.config.js

eth, klay send transaction 기능 개발
1. home 컴포넌트 로직 수정
2. send transaction 개발
closes #85

send transaction 개발

---

src/app/controller.js
src/app/controllers/token-controller.js
src/ui/components/asset-list/asset-item/asset-item.jsx
src/ui/components/asset-list/asset-list.jsx
src/ui/pages/assets.jsx
src/ui/pages/create-token.jsx
src/ui/pages/transfer/estimate-token-gas.jsx
src/ui/pages/transfer/input-address-token.jsx

Preview token

---

src/app/constants/network.js
src/app/controller.js
src/app/controllers/history-controller.js
src/ui/components/account-view/dropdown-menu/dropdown-menu.jsx
src/ui/components/eth-transaction-list/eth-transaction-item/eth-transaction-item.jsx
src/ui/components/eth-transaction-list/eth-transaction-item/eth-transaction-item.scss
src/ui/components/eth-transaction-list/eth-transaction-item/index.js
src/ui/components/eth-transaction-list/eth-transaction-list.jsx
src/ui/components/eth-transaction-list/index.js
src/ui/components/klay-transaction-list/index.js
src/ui/components/klay-transaction-list/klay-transaction-item/index.js
src/ui/components/klay-transaction-list/klay-transaction-item/klay-transaction-item.jsx
src/ui/components/klay-transaction-list/klay-transaction-item/klay-transaction-item.scss
src/ui/components/klay-transaction-list/klay-transaction-list.jsx
src/ui/data/history/history.api.js
src/ui/data/history/history.hooks.js
src/ui/pages/assets.jsx
src/ui/pages/home.jsx
src/ui/pages/routing.jsx
src/ui/pages/tx-history.jsx
src/ui/pages/welcome.jsx
tailwind.config.js

ethereum network 일 때 etherscan을 통해 트랜잭션 내역을 보여주는 기능 추가
- token의 경우에는 수정 필요
- klaytn network 작업 필요
close #91

트랜잭션 내역 조회 페이지 개발

---

src/app/controllers/keyring-controller.js
src/app/lib/hd-keyring.js
src/ui/data/account/account.api.js

Mnemonic add account

---

src/app/controllers/history-controller.js
src/ui/components/account-view/selected-account/selected-account.jsx
src/ui/components/asset-list/asset-item/asset-item.jsx
src/ui/components/asset-list/asset-item/asset-item.scss
src/ui/components/eth-transaction-list/eth-transaction-item/eth-transaction-item.jsx
src/ui/components/klay-transaction-list/klay-transaction-item/klay-transaction-item.jsx
src/ui/data/history/history.hooks.js
src/ui/pages/tx-history.jsx

트랜잭션 history - 단위 표시 로직 수정
1. ethereum network balance 단위를 eth, goerli일 때와 token일 때 표시하는 것 수정
2. baobab graphql에 contract 추가 후 단위표시 로직 추가
close #refactor/token-symbol

refactor: history unit 수정

---

src/app/background.js
src/app/controller.js
src/app/controllers/keyring-controller.js
src/app/controllers/token-controller.js
src/app/lib/hd-keyring.js
src/app/messages.js
src/ui/data/account/account.api.js
src/ui/data/account/account.hooks.js
src/ui/pages/export-account.jsx
src/ui/pages/home.jsx

- token: switchAccounts 수정
- keyring: 니모닉 복구하기 기능 추가

feat: Add getMnemonic code

---

public/notification.html
public/popup.html
src/app/background.js
src/app/controller.js
src/app/controllers/transactions/transaction-controller.js
src/app/messages.js
src/ui/data/transaction/transaction.api.js
src/ui/data/transaction/transaction.hooks.js
src/ui/pages/transaction/estimate-gas.jsx
src/ui/pages/transaction/transaction.jsx
src/ui/pages/transfer/estimate-token-gas.jsx
src/ui/pages/transfer/input-address-token.jsx
src/ui/pages/transfer/transfer.jsx
src/ui/store/transaction.js

token gas limit을 estimateGas api를 통해 가져와서 갱신하도록 로직 추가
1. transaction controller에 token일 경우 estimate gas api 호출하는 로직 추가
2. token transfer시 gas estimate하는 로직 추가
close #refactor/token-gas

refactor: token gas estimate 로직 수정

---

src/app/controllers/keyring-controller.js
src/ui/components/account-view/dropdown-menu/dropdown-menu.jsx
src/ui/components/account-view/dropdown-menu/dropdown-menu.scss

account identities에 키링 type 정보 추가
- 계정리스트에서 외부 가져옴 라벨 표시위해서 추가 (HD Keyring 인지 Simple Keyring인지 구분 값)
ref #feature/account-list-add-label

account identities에 키링 type 정보 추가

---

src/app/constants/network.js

Polygon network
